[2023-10-29T00:51:40.038+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2023-10-29T00:51:35.766638+00:00 [queued]>
[2023-10-29T00:51:40.042+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2023-10-29T00:51:35.766638+00:00 [queued]>
[2023-10-29T00:51:40.043+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-29T00:51:40.048+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2023-10-29 00:51:35.766638+00:00
[2023-10-29T00:51:40.053+0000] {standard_task_runner.py:57} INFO - Started process 49 to run task
[2023-10-29T00:51:40.056+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2023-10-29T00:51:35.766638+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp8uyvkru2']
[2023-10-29T00:51:40.058+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask s3_upload
[2023-10-29T00:51:40.093+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2023-10-29T00:51:35.766638+00:00 [running]> on host c6e1457c8c5f
[2023-10-29T00:51:40.144+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='httrinh' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T00:51:35.766638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-29T00:51:35.766638+00:00'
[2023-10-29T00:51:41.044+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2023-10-29T00:51:41.046+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 12, in upload_s3_pipeline
    upload_to_s3(s3,file_path,AWS_BUCKET_NAME,file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2023-10-29T00:51:41.071+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20231029T005135, start_date=20231029T005140, end_date=20231029T005141
[2023-10-29T00:51:41.087+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task s3_upload ('NoneType' object has no attribute 'split'; 49)
[2023-10-29T00:51:41.125+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-29T00:51:41.146+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
